-- =============================================================================
-- Ethnos_API — required database objects (operator-side DDL contract)
-- =============================================================================
-- The API is strict consumer-only: it NEVER executes this file. This is the
-- single, canonical record of the schema changes the API needs from the
-- operator pipeline. It replaces the former per-request `calls/` log.
--
-- Workflow:
--   1. Operator reviews and applies the statements below against `data`.
--   2. Operator regenerates the schema snapshot:
--        mysqldump -d --routines --events --order-by-primary --single-transaction \
--          --compact --skip-comments --skip-tz-utc --default-character-set=utf8mb4 \
--          data > backups/data.schema.$(date +%Y-%m-%d).sql
--   3. The API is updated to consult the new snapshot.
--
-- Statements are idempotent. Empty a section once the operator confirms it is
-- applied.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- (no pending objects)
-- -----------------------------------------------------------------------------

-- Previously applied (recorded in backups/data.schema.<date>.sql):
--   * works.latest_publication_year + idx_works_latest_pub_year, maintained by
--     sp_refresh_works_publication_years.
--   * subjects.total_works (INT, denormalized COUNT(DISTINCT ws.work_id) per
--     subject) + idx_subjects_total_works, maintained by
--     sp_refresh_subjects_total_works_simple. Applied 2026-07-21: 168,815 of
--     169,159 subjects populated. Backs /subjects/statistics work-linkage stats
--     and the works_count on /subjects/{id}, /subjects/{id}/children,
--     /subjects/{id}/hierarchy without the 15.8M-row work_subjects join.
--   * idx_works_reference_count (works.reference_count), backing the indexed
--     ORDER BY on /works?sort_by=references_count. Applied 2026-07-21.
