-- ============================================================================
-- Strip emoji string literals from validation procedures — 2026-04-14
-- ============================================================================
--
-- Filed by: Ethnos_API project (consumer-only).
-- Target:   `data` database.
-- Scope:    cosmetic cleanup of `sp_test_system` and `sp_validate_schema_fixes`
--           to remove emoji characters embedded in their output message
--           string literals.
--
-- Status:   PENDING.
--
-- Why
-- ---
-- Project rule forbids emojis in any tracked code, config, log output or
-- documentation. The live DB currently holds two validation procedures
-- whose bodies contain embedded emoji literals inside SELECT / SET string
-- outputs:
--
--   - `sp_validate_schema_fixes`: emits "Tabelas temporarias funcionando",
--     "Procedure sp_generate_name_signature: ...", "Indice
--     idx_authorships_created_at validado", "TODAS AS CORRECOES APLICADAS
--     COM SUCESSO", "<N> ERROS ENCONTRADOS. VERIFIQUE OS LOGS." — each
--     prefixed with check / cross / warning emojis.
--   - `sp_test_system`: analogous output messages.
--
-- When the project regenerates `database/data.schema.sql` via
-- `scripts/maintenance/publications/regenerate_schema_dump.sh`, the helper
-- currently post-filters the dump through a `perl -CSD -pe 's/<emoji
-- ranges>//g'` pipeline so the tracked file stays clean. That is a
-- consumer-side workaround. The source of truth is the live DB, and the
-- cleanest fix is to strip the literals at the procedure level so the
-- dump and the live state stay byte-for-byte identical without any
-- post-processing.
--
-- Ethnos_API project never calls these procedures directly. They are
-- operator-owned maintenance routines. After this request lands, the
-- consumer-side `perl` filter in `regenerate_schema_dump.sh` can stay as
-- a belt-and-suspenders guard but it becomes a no-op.
--
-- Proposed change
-- ---------------
-- Drop and recreate both procedures with the same logic and the same
-- string outputs, minus the emoji prefixes. Replace "<check-emoji>
-- <text>" with plain "OK: <text>" and "<cross-emoji> <text>" with
-- "FAIL: <text>"; replace "<double-check-emoji> ALL CORRECTIONS APPLIED
-- WITH SUCCESS" with plain "ALL CORRECTIONS APPLIED WITH SUCCESS"; replace
-- "<warning-emoji> N ERRORS FOUND..." with "WARN: N ERRORS FOUND...".
--
-- The operator should re-read the current bodies of both procedures from
-- the live DB, apply the textual substitutions, and `DROP PROCEDURE` +
-- `CREATE PROCEDURE` each one with the cleaned body. The agent deliberately
-- does not include a full body rewrite here because these are cosmetic
-- validation routines that may be edited by the operator for other reasons
-- between filing and application; freezing the body in this file would
-- invite merge conflicts.
--
-- Verification (read-only)
-- ------------------------
--
--   SELECT ROUTINE_NAME
--   FROM information_schema.ROUTINES
--   WHERE ROUTINE_SCHEMA = DATABASE()
--     AND ROUTINE_NAME IN ('sp_test_system', 'sp_validate_schema_fixes')
--     AND (
--       ROUTINE_DEFINITION REGEXP '[\\x{2600}-\\x{27BF}]' OR
--       ROUTINE_DEFINITION REGEXP '[\\x{1F300}-\\x{1FAFF}]'
--     );
--   -- Expected: zero rows.
--
-- After the operator applies the change, the project regenerates the
-- schema dump and the `perl` filter becomes a no-op.
--
-- Rollback
-- --------
-- Low priority — rollback is purely cosmetic. If needed, restore either
-- procedure from `git show <pre-change>:database/data.schema.sql` where
-- the bodies are still visible inside the schema-dump history prior to
-- the `perl` filter being added.
